syncfusion/maui-toolkit

maui/src/TextInputLayout/SfTextInputLayout.Methods.cs
The issue occurs due to a lack of null checks in the InputView's TextChanged event.
- Added null checks for the Text property using the null conditional operator to prevent crashes when the text is set to null.
- Ensure that when the text is set to null or empty, the hint state is updated correctly by setting IsHintFloated to false. 
- 
Fixes #11 
https://github.com/user-attachments/assets/f8b905e2-3253-45ff-b6b4-7615b9a9ef8f
https://github.com/user-attachments/assets/ea1a92ef-54cf-49e5-b63d-836e5dd1e3eb
=> Resolved Null Crash and Improved Hint Behavior in SfTextInputLayout

maui/src/Core/Extensions/CanvasExtensions.Windows.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Navigation/SfTabViewUnitTests.cs
The issue originates from the DrawText method in the CanvasExtensions.Windows.cs class, which does not return the correct string path value when the application is in an unpacked state.
Added the GetFontFamily static method to return the font family based on whether the application is in an unpacked or packed state. The application state is determined by the newly added IsPackaged static method from the PackagedAppHelper static class.
Fixes #12
=> Resolved the exception when setting the FontFamily property in .NET MAUI controls on Windows.

maui/src/TabView/Control/HorizontalContent/SfHorizontalContent.cs, maui/src/TabView/Control/SfTabBar.cs
This issue occurred because the content's width and height were not updated when resizing the output window.
Removed the dynamic width and height changes when the measure content method was triggered. To address the continuous repositioning issue, we’ve optimized the handling of translation during window resizing:
Improved Animation Control: When the selection is being processed, we now update the TranslationX property directly without triggering unnecessary animations, ensuring smoother performance.
This update ensures that the TabView behaves more efficiently during resizing, improving performance and stability, particularly when the final tab is selected.
Fixes https://github.com/syncfusion/maui-toolkit/issues/34
https://github.com/user-attachments/assets/eeb643b8-1226-40f9-a19c-f1b5930 …
=> Resolved the Content Resize Issue in MAUI TabView When Output Window is Resized.

maui/src/TabView/Control/HorizontalContent/SfHorizontalContent.cs, maui/src/TabView/Control/SfTabBar.cs, maui/src/TabView/Control/SfTabView.cs
The TabView control takes more time to load initially because all tab items are loaded upfront. Customers require a feature to support the lazy loading of tab items and enhance performance.
Introduced a new public property, EnableVirtualization, in the TabView control. When enabled, only the selected tab item is loaded during the initial rendering. Placeholder views (BoxView) are used for non-selected tab items, reducing the initial load time. After the initial load, the content of a tab item will load when you either navigate to the next tab by selecting it from the TabBar or swipe to the next item.
- Addressed the performance issue with the TabView control's initial loading.
- Improved load times by introducing lazy loading through the EnableVirtualization feature.
- Ensured that only …
=> Provide the EnableVirtualization property to the TabView control.

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
A new issues and feature report template has been added to get proper details when a report is logged.
=> Added new issues and feature report template

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Cleared syntax error in new bug and feature templates
=> Cleared syntax error in new bug and feature templates

maui/src/AssemblyInfo.cs, maui/src/BottomSheet/BottomSheetBorder.cs, maui/src/BottomSheet/Enum.cs, maui/src/BottomSheet/SfBottomSheet.Windows.cs, maui/src/BottomSheet/SfBottomSheet.cs, maui/src/BottomSheet/SfBottomSheet.iOS.cs, maui/src/BottomSheet/StateChangedEventArgs.cs, maui/src/Core/Theme/Resources/DefaultTheme.xaml, maui/src/Themes/SfBottomSheetStyle.xaml, maui/src/Themes/SfBottomSheetStyle.xaml.cs
A `BottomSheet` control is a user interface component used in mobile and desktop applications that slides up from the bottom of the screen to display supplementary content or actions, allowing users to interact with additional information without navigating away from the main screen.
**Multiple states**
Control the BottomSheet’s transitions between different states, such as FullExpanded, HalfExpanded, Collapsed, and Hidden.
**Control state navigation**
Customize the allowed states for the BottomSheet to control its expandability. Options include FullExpanded, HalfExpanded, and All.
**Popup mode**
Activate the BottomSheet as a modal dialog.
**Adjust the sheet height** 
Supports adjusting the height of the BottomSheet in FullExpanded, HalfExpanded, and Collapsed states.
**Customizing the …
=> Implementation of the SfBottomSheet Control in MAUI Toolkit

maui/src/Carousel/Platform/Android/PlatformCarousel.Android.cs
- The issue occurs because the ItemHeight and ItemWidth properties are not recalculated after the carousel is created, particularly during the SizeChanged event, causing images not to display on Android
- Adjusted the SfCarousel to reallocate and recalculate its layout whenever ItemHeight or ItemWidth is updated for linear mode.
- Ensured proper virtual view measurements for the carousel.
Fixes #36
=> Carousel linear mode dynamic image changes committed

maui/src/BottomSheet/SfBottomSheet.cs, maui/src/Themes/SfBottomSheetStyle.xaml, maui/src/Themes/SfBottomSheetStyle.xaml.cs
An unwanted namespace was exposed in the MAUI Toolkit, leading to potential conflicts.
Removed the unwanted namespace from the MAUI Toolkit. Ensured that the affected functionality (e.g., BottomSheet control) is not impacted by this change.
This change resolves the namespace conflict for the BottomSheet control.
- Not applicable
- Not applicable
=> Remove the unwanted namespace

maui/src/TextInputLayout/SfTextInputLayout.Methods.cs, maui/src/TextInputLayout/SfTextInputLayout.Properties.cs, maui/src/TextInputLayout/SfTextInputLayout.cs
**iOS:** The ReturnType = "NEXT" of Entry not working, because the Opacity of the Entry was set to 0.
**Android:** The ReturnType property was not being set at all, possibly due to a native restriction.
**iOS:** Adjusted the Opacity value from 0 to a minimal value (0.00001), ensuring the ReturnType property works as expected.
**Android:** Added a condition to explicitly reset the native property value (ReturnType) to handle native restrictions.
Fixes [#51](https://github.com/syncfusion/maui-toolkit/issues/51)
https://github.com/user-attachments/assets/9b2aef95-9ecb-4b31-a213-a21cd96389d1
iOS
https://github.com/user-attachments/assets/b0a6263e-3ec6-4dfa-a849-786cd2f68bbf
Android
https://github.com/user-attachments/assets/17016eb8-8ae4-4720-bb2e-e06cdbd47fa8
=> Resolved Entry ReturnType = "NEXT" Not Working with SfTextInputLayout Issue

maui/src/BottomSheet/SfBottomSheet.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Navigation/SfTabViewUnitTests.cs
The root cause of the issue was that the IsOpen property was using one-way binding by default. This means that changes in the UI wouldn't automatically update the underlying data or model. Since two-way binding is necessary for reflecting changes in both directions (from the UI to the model and vice versa), the one-way binding setup was preventing the expected behavior of the IsOpen property, causing issues with how it synchronized between the UI and data.
To resolve this issue, the binding mode for the IsOpen property was changed to two-way binding (BindingMode.TwoWay). This allows changes made in the UI (such as opening or closing the bottom sheet) to update the underlying data and vice versa, ensuring proper synchronization between the UI and the bound data.
Fixes #57 …
=> Resolve the issue of the IsOpen property of BottomSheet didn't work properly when binding the value to the property.

maui/src/NumericEntry/Event/ValueChangedEventArgs.cs, maui/src/NumericEntry/SfNumericEntry.Methods.cs, maui/src/NumericEntry/SfNumericEntry.cs, maui/src/NumericEntry/SfNumericUpDown.cs, maui/src/TextInputLayout/SfTextInputLayout.Methods.cs, maui/src/TextInputLayout/SfTextInputLayout.Properties.cs, maui/src/TextInputLayout/SfTextInputLayout.cs
**Improve Long Press Behavior:** Updated the logic for long press code using CancellationTokenSource to restrict unintended increments.
**Resolve AutoReverse Color Issue:** Fixed the issue where the up or down button color appeared disabled when the minimum or maximum value was reached, and AutoReverse was set to true.
**Toolbar Item Issue:** Resolved the issue where the toolbar item was not visible on the latest devices and did not change its size while rotating.
**Improve Inaccessibility:** Enhanced the accessibility for NumericUpDown when the button is disabled.
**Long Press:** The increment behavior was not properly managed due to missing cancellation logic.
**AutoReverse Color:** The disabled color was not correctly restricted when AutoReverse was enabled.
**Toolbar Item:** …
=> Enhancements and Bug Fixes: Long Press, AutoReverse, Toolbar Item, and Accessibility Improvements

maui/src/SegmentedControl/Interface/ISegmentInfo.cs, maui/src/SegmentedControl/SfSegmentedControl.cs, maui/src/SegmentedControl/Views/Keyboard/KeyNavigationView.cs, maui/src/SegmentedControl/Views/OutlinedBorderView.cs, maui/src/SegmentedControl/Views/SegmentLayout.cs, maui/src/SegmentedControl/Views/Selection/SelectionView.cs
The keyboard navigation for the SegmentedControl view is not handled properly when navigating between controls using the Tab key.
Segment control is not  focusable when navigating using the Tab key. Setting **IsTabStop = true to MAUI native platform view** ensures that the control is recognized as part of the tab navigation flow.
This change is related to UI interaction, hence not applicable
Fixes [67](https://github.com/syncfusion/maui-toolkit/issues/67)
https://github.com/user-attachments/assets/8fddbbee-5900-4f90-9135-76c948640416
https://github.com/user-attachments/assets/4be776a4-90c2-41e6-a003-960756887722
=> SegmentedControl does not receive Focus when pressing the Tab key on Windows

maui/src/SegmentedControl/Interface/ISegmentInfo.cs, maui/src/SegmentedControl/SfSegmentedControl.cs, maui/src/SegmentedControl/Views/SegmentItemView.cs, maui/src/SegmentedControl/Views/SegmentLayout.cs
Segmented control does not support the default keyboard navigation for the segmented item in the windows platform.
Customer given semantics description is not set to the SegmentedItemView in the windows platform.
When using keyboard navigation with the narrator enabled, the segmented item will read the customer-provided semantics description in the view.
Removed the custom keyboard navigation for the segmented control and used the default framework navigation. Fixed the narrator accessibility issue to ensure it reads the customer-provided semantics description.
Fixes #
[77](https://github.com/syncfusion/maui-toolkit/issues/77)
https://github.com/user-attachments/assets/5587284e-0ea8-4ac5-92d8-e84e05bf0795
https://github.com/user-attachments/assets/7d81f0e9-f74b-431f-aab0-80610a026238
=> Fixed the segmentedcontrol keyboard navigation and accessibility issue in windows

maui/src/PullToRefresh/SfPullToRefresh.cs
**Android:** The main issue was the inclusion of the IsActualRefreshing condition in the Measure and Arrange content. This condition is unnecessary, and as a result, the pullable content measure and arrange was not being called when it was placed shimmer as a pullable content of PullToRefresh..
**Android:**
- Since IsActualRefreshing is not necessary, we removed the condition from both the Measure and Arrange content.
- As a result, the measure content for the shimmer is now called properly.
Fixes [#72](https://github.com/syncfusion/maui-toolkit/issues/72)
https://github.com/user-attachments/assets/a49231eb-3a0d-4d42-b760-3685cf909352
https://github.com/user-attachments/assets/deebedc0-5852-463f-890d-05bd3d16bfe2
=> 938933-Shimmer effect does not display when added inside the PullToRefresh.

maui/src/SegmentedControl/Views/SegmentItemView.cs
The segmented control was applying touch effects to all segments by default, even when a custom template was used. This led to an unintended visual effect while pressing on a segment when templates were used.
- Updated the `OnTouch` event in the `SegmentItemView` to check if a `SegmentTemplate` is set before applying touch effects.  
- The effects are now only applied if no custom template is used.  
Fixes : https://github.com/syncfusion/maui-toolkit/issues/88
https://github.com/user-attachments/assets/abe2e472-e6c4-4dd0-a771-8541e97a0ec5
https://github.com/user-attachments/assets/6e5a0c3c-7d20-49c4-8af6-1babc0cc89e9
=> Remove Ripple Effect applied when segment item template added

maui/src/BottomSheet/BottomSheetBorder.cs, maui/src/BottomSheet/SfBottomSheet.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Navigation/SfBottomSheetUnitTests.cs
1. Scroll occurs both in the bottom sheet and its child in iOS.
2. Updated padding to the entire bottom sheet.
3. The overlay grid disappears suddenly when IsModal is set to false or transitioned to a hidden or collapsed state.
4. The bottom sheet gets stuck when swiped and released at some points.
1. When scroll view is placed as a child in bottom sheet content, restricted scroll based on touch points.
2. Default padding(5) is provided to the entire bottom sheet.
3. Provided animation to overlay in the bottom sheet.
4. Improved nearest point of bottom sheet state when swiped.
https://github.com/syncfusion/maui-toolkit/issues/96
https://github.com/syncfusion/maui-toolkit/issues/97
=> Improve animation for the Maui Bottom sheet control

maui/src/NavigationDrawer/SfNavigationDrawer.Android.cs
The issue arises due to incorrect initialization of touch coordinates, preventing proper detection of scroll gestures on Android when items exceed the height of the scroll view.
To resolve the scrolling issue, the touch coordinates are now correctly updated:
- `_downX` and `_downY` are set using the touch event's current X and Y positions with `ev.GetX()` and `ev.GetY()`.
- `_initialPoint` is updated to `currentTouchPoint`, ensuring the touch start point is accurately stored.
Fixes #[106](https://github.com/syncfusion/maui-toolkit/issues/106)
https://github.com/user-attachments/assets/54ddd516-4600-44f3-82b9-8ccae38bde53
https://github.com/user-attachments/assets/825984f8-17b3-4150-af48-ad178496b96d
=> Improve the touch interaction in Maui toolkit Navigation drawer.

maui/samples/Gallery/SampleList/CartesianChartSamplesList.xml, maui/samples/Gallery/Samples/CartesianChart/FastScatterChart/FastScatterChart.xaml, maui/samples/Gallery/Samples/CartesianChart/FastScatterChart/FastScatterChart.xaml.cs, maui/samples/Gallery/Samples/CartesianChart/FastScatterChart/FastScatterSeriesViewModel.cs, maui/src/Charts/Segment/FastScatterSegment.cs, maui/src/Charts/Series/CartesianSeries.cs, maui/src/Charts/Series/FastLineSeries.cs, maui/src/Charts/Series/FastScatterSeries.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/ChartSeriesUnitTests.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/DefaultTests/DefaultSegmentUnitTest.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/DefaultTests/SeriesDefaultTestsPartial.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/Features/SegmentUnitTests.cs
The Fast Scatter Series in .NET MAUI Charts to efficiently render large datasets with improved performance. Unlike the standard Scatter Series, the Fast Scatter Series is optimized for handling thousands or even millions of data points without compromising rendering speed or UI responsiveness.
* https://github.com/syncfusion/maui-toolkit/pull/116
- Performance: Faster rendering compared to traditional Scatter Series, especially when handling large datasets.
- Scalability: Capable of plotting millions of data points without performance degradation.
- Smooth Interactions: Provides a fluid user experience when zooming and panning.
- Optimized for Real-Time Data: Best suited for applications with frequently updating data points.
=> Implement the Fast Scatter series support in the Cartesian Chart in MAUI Toolkit

maui/src/Popup/SfPopup/SfPopup.cs
The issue occurs due to framework changes in version 9.0.50 [https://github.com/dotnet/maui/pull/20154].
We will set _popupOverlayContainer visibility to false after dismissing the popup.
We will set _popupOverlayContainer as the parent to popupView on display. Due to the framework changes, the IsVisible property of _popupView is set to false when reopening with the same instance of the popup, since _popupOverlayContainer visibility will now be false. We will set the visibility of _popupOverlayContainer to true in a later section and _popupViewvisibility will still remains false.
To resolve the issue, setting the IsVisible property of the _popupOverlayContainer to true when setting it as parent to the _popupView.
[[Bug] SfPopup does not show up after repeated openning · Issue #139 · …
=> Fixed SfPopup does not show up after repeated opening issue.

maui/src/NumericEntry/SfNumericEntry.cs
When the IsVisible property is initially set to false and then changed to true, the SfNumericEntry control does not gain focus and remains in a disabled state.
Handled the IsVisible property of the Entry based on the visibility state of the SfNumericEntry control to ensure it regains focus and functions correctly.
Fixes #138 
https://github.com/user-attachments/assets/dfcc0212-2a89-407b-b822-11ca110fc7f2
https://github.com/user-attachments/assets/f6dcbcd4-795b-46d5-8a8d-a82f2f98eb3b
=> Resolved the issue where Numeric Entry does not gain focus when its visibility is changed.

maui/src/Core/AppHostBuilder.cs, maui/src/Syncfusion.Maui.Toolkit.csproj, maui/src/Syncfusion.Maui.Toolkit.props
The built-in MauiMaterialAssets font icons in the .NET MAUI toolkit are not rendered in the application.
The MauiMaterialAssets file was missing from the NuGet package, causing the icons not to render in the application.
Manually included the MauiMaterialAssets file inside the NuGet package to ensure proper rendering of the icons.
=> Resolved MauiMaterialAssets font icon issue

maui/src/Core/Extensions/CanvasExtensions.Windows.cs, maui/src/TextInputLayout/SfTextInputLayout.Methods.cs
The crash occurred on the Windows platform when the container width and text width were reduced to a negative value because of padding applied to the parent layout of the TextInputLayout control.
Implemented restrictions to prevent negative value updates for container width and text width, ensuring stability in such scenarios.
Fixes #136
https://github.com/user-attachments/assets/24bb5642-e3c3-4aaa-be67-a0da56c1db0d
https://github.com/user-attachments/assets/73dd93ca-60b6-4e6c-b083-0583a77a54c5
=> Resolved the crash in TextInputLayout when resizing the Window.

maui/src/Charts/SfCartesianChart.cs
When clear the annotations collection the view annotation was not cleared in MAUI Charts.
Reset part of the code was not implemented. 
Not tested this case previously.
**Action taken:**
- The ResetAnnotation method was implemented to clear all annotations. It traverses the annotation layout collection in reverse and removes view item only because, in Annotation layout have annotation drawable view and this was need for again for other drawable annotations. If clear, the invalidate drawable was called and cleared. So, removed the view only from layout. 
No
- The solution involves implementing a loop within the ResetAnnotation method to remove all views (ViewAnnotation.View) from the AnnotationLayout.
**Before changes:**
https://github.com/user-attachments/assets/4d28d750-fb6f-4183-a9e0-0c96 …
=> Fix the view annotation was not cleared issue when clear the annotations collection in MAUI Charts.

maui/src/BottomSheet/SfBottomSheet.cs
When the bottom sheet transitions quickly to the half or fully expanded state, the state changed event is not triggered
Updated the StateChanged event to handle negative touch points received beyond the bounds of the bottom sheet, ensuring accurate state changes.
Fixes: https://github.com/syncfusion/maui-toolkit/issues/152
Resolved an issue where the StateChanged event failed to trigger due to touch inputs with negative coordinates outside the bottom sheet’s bounds, causing inaccurate state tracking.
https://github.com/user-attachments/assets/2af53ab4-6f15-4108-89d7-d8b70ff0761f
https://github.com/user-attachments/assets/000dbd68-7eeb-4518-a891-18741ae35e3c
=> BottomSheet StateChanged Event Not Triggering on Negative Touch Inputs

maui/samples/Gallery/Samples/PullToRefresh/ListViewPullToRefresh/View/ListViewPullToRefresh.xaml.cs, maui/samples/Gallery/Samples/PullToRefresh/PullToRefreshView/View/PullToRefreshView.xaml.cs
**Windows:** 
The main cause of the issue was when we navigate to next page, DisconnectHandlers are not called when navigating to the next page.
**Windows:**
- Before navigating to another page, we have to disconnect it manually in the sample level
- So that, it works properly
https://github.com/user-attachments/assets/759ee84e-7e0a-45fd-9578-c47f3bc14ac9
https://github.com/user-attachments/assets/474b23ed-b4dc-4d1c-87a3-48727c9c0430
=> 954484-Fix the PullToRefresh issues in the Maui Toolkit that occurs during testing.

maui/src/NumericEntry/SfNumericEntry.cs, maui/src/NumericEntry/SfNumericUpDown.cs, maui/src/TextInputLayout/SfTextInputLayout.Methods.cs, maui/src/TextInputLayout/SfTextInputLayout.Properties.cs, maui/src/TextInputLayout/SfTextInputLayout.cs
Accessibility was not functioning correctly when Picker and NumericEntry were placed inside the TextInputLayout control.
The issue occurred because accessibility for the Picker and numeric control was explicitly restricted within the TextInputLayout implementation.
Removed the accessibility restriction for the Picker control.
Enabled accessibility support for both NumericEntry and its associated up/down buttons.
#171 
https://github.com/user-attachments/assets/096101c6-4c3c-45b8-b687-a5a209df9311
https://github.com/user-attachments/assets/f96532e5-459b-4ef7-9e6e-bf6eec36abc2
=> Resolve Accessibility Issue in TextInputLayout

maui/src/BottomSheet/SfBottomSheet.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Navigation/SfBottomSheetUnitTests.cs
The transition animation lacked customization, as the duration was fixed and not configurable through the API.
Introduced **AnimationDuration** property to allow developers to configure the duration of the bottom sheet transition animations, enabling smoother or faster UI experiences based on application requirements.
API Name: AnimationDuration
Namespace: Syncfusion.Maui.Toolkit.BottomSheet
Input type: bool
Access specifier: public
https://github.com/syncfusion/maui-toolkit/issues/99
**Default Animation Duration**
https://github.com/user-attachments/assets/37af4f31-fbde-4ac9-a94d-8d2a2cc45a20
**Animation Duration = 1000**
https://github.com/user-attachments/assets/a9e86c14-d5a1-4ee5-9fee-463a107e20e4
=> Provide animation duration support for Bottom sheet control

maui/src/Charts/Behaviors/ChartTooltipBehavior.cs, maui/src/Charts/ChartBase.cs, maui/src/Charts/Series/BoxAndWhiskerSeries.cs, maui/src/Charts/Series/CartesianSeries.cs, maui/src/Charts/Series/ChartSeries.cs, maui/src/Charts/Series/HiLoOpenCloseSeries.cs, maui/src/Charts/Series/PieSeries.cs, maui/src/Charts/Series/PolarSeries.cs, maui/src/Charts/Series/RadialBarSeries.cs, maui/src/Charts/Series/StackingAreaSeries.cs, maui/src/Charts/Series/StackingColumnSeries.cs, maui/src/Charts/Series/StackingLineSeries.cs, maui/src/Charts/SfFunnelChart.cs, maui/src/Charts/SfPolarChart.cs, maui/src/Charts/SfPyramidChart.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/DefaultTests/BehaviorDefaultTests.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/Features/ChartUnitTests.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Chart/Features/SegmentUnitTests.cs
When setting the AppThemeBinding to tooltipBehavior background color, the tooltip background was not updated when the theme was changed.
https://github.com/syncfusion/maui-toolkit/issues/159 
To set the internal property values to the behavior background property, the binding property was overridden to the value property, so the appthemebinding values were not dynamically updated. 
Set the Behavior background property value to tooltipinfo. If it is null means to set the tooltip background that was applied in the resource key, and if it is also null means to set the default values for the tooltip background.
1. Test with Appthemebinding for Background property and change the theme dynamically and load time.
3. Test with Resource key for Tooltipbackground property and change the theme …
=> I159-Fix tooltip background was not updated when the theme was changed.

maui/src/OtpInput/SfOtpInput.cs
In the SfOtpInput control, the `GetPlaceHolder()` method appends `\0` (null) characters to pad the placeholder text to the required Length. These null characters unintentionally propagate into the `Value` property, particularly when Type is set to Number.
This behavior causes:
Value being polluted with `\0` characters (e.g., "1\0\0" for Length=3)
Incorrect entry behavior: Deleting the first character shifts the second entry's value to the first, breaking the position-to-box integrity.
**Input Type Fix (Number):** Modified internal logic to prevent `\0` padding from affecting the actual Value property.
**Backspace Handling:** Enforced a strict one-to-one mapping between value positions and UI boxes, preventing value shifting on deletion.
**Value Sanitization (Optional Enhancement):** …
=> Resolved the ValueChanged event issue in SfOtpInput.

maui/src/SegmentedControl/Helper/SegmentViewHelper.cs, maui/src/SegmentedControl/Views/SegmentItemView.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Buttons/SfSegmentedControlUnitTests.cs
When StrokeThickness is zero, the totalwidth is equal to maxWidth. So the keyFocusedViewPadding is not reduced from the maxWidth. This causes the segmented control to get cut.
This behavior causes:
Value is added with the keypadding causing the control to get cropped.
Added the keypadding to the totalwidth before comparing with the max width.
Fix : [Pr 1190](https://gitea.syncfusion.com/essential-studio/maui-toolkit/pulls/1190)
Prevents the extra padding and renders within the given width
**Windows**
**Android**
**Mac**
**iOS**
**Windows**
**Android**
**Mac**
**iOS**
=> 964655- Fix for MAUI Segmented control right side cropped when the stroke thickness is 0

maui/src/TextInputLayout/SfTextInputLayout.Properties.cs, maui/src/TextInputLayout/SfTextInputLayout.cs
The use of Opacity = 0 for certain UI elements excluded them from the Tab key navigation hierarchy, as the system did not consider them visible or focusable.
To address this, we introduced a minimal saturation opacity value that keeps elements visually hidden but logically present for accessibility and keyboard navigation. This update ensures the TextInputLayout is included in the focus traversal order via Tab key navigation. The fix applies consistently across supported platforms including macOS (via MacCatalyst), Windows, Android, and iOS, ensuring unified behavior
Fixes https://github.com/syncfusion/maui-toolkit/issues/178
https://github.com/user-attachments/assets/4f21e5f4-facb-4a7e-bb27-3bb4673e9e0d
https://github.com/user-attachments/assets/a4777761-8738-4d00-bbf3-3fb5df610595
=> Resolved the Tab key navigation issue in TextInputLayout

maui/src/Expander/ExpanderHeader.cs
When a user long-presses on a collapsed SfExpander header and slides their finger off the expander before releasing (which cancels the expansion), the arrow icon remains stuck in the pressed color instead of returning to the configured `HeaderIconColor`.
This issue occurs because:
1. On press: The icon color correctly changes to `PressedIconColor`
2. On cancelled/released touch: Only the ripple effect was reset, but the icon color was never restored
1. Set `HeaderIconColor` to a distinct color (e.g., Blue)
2. Set `PressedIconColor` to a different color (e.g., Red) 
3. Long press on expander header → Arrow turns red
4. While holding, slide finger off the header area
5. Release finger → Arrow stays red instead of returning to blue
Added icon color restoration logic in the `OnTouch` method …
=> Fix SfExpander arrow color not restoring after cancelled touch gesture

maui/src/Button/SfButton.Methods.cs, maui/src/Core/Extensions/StringExtensions.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Buttons/SfButtonUnitTests.cs
The issue was in the MeasureContent method where the width calculation for text wrapping didn't consider the available width constraint. When no explicit WidthRequest was set, the method used the button's natural text width (which would be very wide for long text) instead of the available layout width, preventing text wrapping.
Modified CalculateWidth method to use available width constraint if the measured width higher than width constraint.
Fixes https://github.com/syncfusion/maui-toolkit/issues/190
=> Resolved the button text does not wrap without explicit Widthrequest

maui/src/BottomSheet/SfBottomSheet.cs
When the AllowedState is set to FullExpanded and the State is set to Collapsed during the initial load, the position and height of the bottom sheet behave inconsistently—its position reflects the FullExpanded state, while its height corresponds to the Collapsed state, resulting in unintended behavior.
Updated the position based on the current state of the bottom sheet.
Issue: https://github.com/syncfusion/maui-toolkit/issues/225
=> Resolved the initial layout issue when AllowedState is set to FullExpanded

maui/src/Button/SfButton.Methods.cs
Cancelled interaction was clearing some effects, but wasn't changing the actual button state.
_isPressed should no longer be true, allowing us to go back to the Normal state
Fixes #228
https://github.com/user-attachments/assets/bfb46abf-f195-49fb-bef9-784df3f02165
https://github.com/user-attachments/assets/72f925ff-56ab-409a-a880-b3d3bca2d655
=> Handle un-pressing button when pointer interaction cancelled

maui/src/BottomSheet/SfBottomSheet.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Navigation/SfBottomSheetUnitTests.cs
When the bottom sheet is opened multiple times, it blocks the touch interactions to the content behind it, where the view's visibility had been handled previously.
Dynamically removed the overlay grid when required based on the states of the bottom sheet.
Issue: https://github.com/syncfusion/maui-toolkit/issues/226
=> [Android] SfBottomSheet backdrop overlay remains visible after dismissal, blocking touch interaction

maui/src/Core/Helper/IconButton/SfIconButton.cs
Following the upgrade to .NET 9, the EffectsView was not applied correctly. This issue stems from directly embedding the EffectsView within the SfIconButton component, which led to improper rendering or behavior.
The issue was resolved by restructuring the layout specifically, by adding the EffectsView as a child of a Grid control. This allowed the clipping to be handled properly, ensuring the expected visual effects were rendered correctly.
Picker Footer View Button Gets Hidden when clicked.
Fixes #
Added Clip Related changes
Before
https://github.com/user-attachments/assets/4d469885-4754-4eb4-aa9d-2776653b4b0a
After:
https://github.com/user-attachments/assets/2111b7fc-a9cc-46bb-95b0-7758185b70f5
=> 972079 - Picker Footer Icon Button Issue

maui/src/OtpInput/SfOtpInput.cs, maui/tests/Syncfusion.Maui.Toolkit.UnitTest/Editors/SfOtpInputUnitTests.cs
The internal logic for the SfOtpInput component's Value property was including non-printable control characters (specifically, null characters like \0) in its string representation. These characters were likely used as internal placeholders for empty OTP cells. When the ValueChanged event was triggered, these control characters were included in the NewValue and OldValue properties of the event arguments. This caused the reported values to be incorrect (e.g., "1a\0\0" instead of "1a"), leading to a data mismatch and unexpected behavior when consuming the event.
- To resolve this, the OnValuePropertyChanged method has been updated to sanitize the OTP values before the ValueChanged event is raised.
- The implementation now explicitly filters both the oldValue and newValue strings to remove …
=> Resolved the OtpInput value mismatch issue for input types text and password.

maui/src/Charts/Axis/ChartAxis.cs
X-axis labels were inconsistently skipped during chart rendering, even when sufficient space was available. This led to a poor user experience, especially in scenarios where label readability was critical.
Bug Report : https://github.com/syncfusion/maui-toolkit/issues/241
The static spacing factor used in the interval count calculation did not account for label rotation. As a result, the algorithm underestimated the number of labels that could be displayed, leading to unnecessary skipping.
The interval count calculation logic was updated to compute the spacing factor based on the label rotation angle. This ensures that the available space is utilized more effectively, and the correct number of intervals is generated for the X-axis.
- Test the axis labels with different LabelRotation …
=> Fixed the issue of Horizontal axis labels skipped despite available space.

maui/src/Core/Legend/AreaBase.cs
Chart rendering throws exceptions on Android devices related to animation settings. This occurs when Developer Options have never been enabled, making animation scale settings inaccessible.
Discussion link: https://github.com/syncfusion/maui-toolkit/discussions/221
The exception was caused by attempting to retrieve the animation scale setting using Settings.Global.GetFloat, which fails if Developer Options were never enabled. This results in a FirstChanceException being logged even though the exception is handled.
To avoid unnecessary exception logging during chart rendering, we replaced the try-catch block with a direct call to Settings.Global.GetFloat using a default value. This ensures smooth behavior even when Developer Options are disabled. The chart now renders with or without …
=> Resolved the issue of exception during animation enabled check by applying a default value

maui/src/Popup/PopupCloseButton.cs, maui/src/Popup/Style/PopupStyle.cs
**Requirement**
The close button foreground color in the Toolkit Popup was not customizable via public API.
**Solution**
Modified the internal CloseButtonIconStroke property to be public accessible, allowing developers to set the foreground color of the close button in the Toolkit Popup. Renamed the API name to CloseIconColor.
**API Summary**
API Name: CloseIconColor
Namespace: Syncfusion.Maui.Toolkit.Popup
Input Type: Color
Access Specifier: public
**FR link**
https://github.com/syncfusion/maui-toolkit/issues/154
**Screenshots**
**Default CloseIconColor**
**CloseIconColor="OrangeRed"**
=> Added property to change close button icon color in Popup
